#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OnlineSurfingShoppingDB")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertChangePassword(ChangePassword instance);
  partial void UpdateChangePassword(ChangePassword instance);
  partial void DeleteChangePassword(ChangePassword instance);
  partial void Insertforget(forget instance);
  partial void Updateforget(forget instance);
  partial void Deleteforget(forget instance);
  partial void InsertLogin(Login instance);
  partial void UpdateLogin(Login instance);
  partial void DeleteLogin(Login instance);
  partial void InsertOrderHistory(OrderHistory instance);
  partial void UpdateOrderHistory(OrderHistory instance);
  partial void DeleteOrderHistory(OrderHistory instance);
  partial void InsertRegister(Register instance);
  partial void UpdateRegister(Register instance);
  partial void DeleteRegister(Register instance);
  partial void InsertShopDetail(ShopDetail instance);
  partial void UpdateShopDetail(ShopDetail instance);
  partial void DeleteShopDetail(ShopDetail instance);
  partial void InsertShopDetial(ShopDetial instance);
  partial void UpdateShopDetial(ShopDetial instance);
  partial void DeleteShopDetial(ShopDetial instance);
  partial void InserttblComplexCategory(tblComplexCategory instance);
  partial void UpdatetblComplexCategory(tblComplexCategory instance);
  partial void DeletetblComplexCategory(tblComplexCategory instance);
  partial void InserttblPaymentHistory(tblPaymentHistory instance);
  partial void UpdatetblPaymentHistory(tblPaymentHistory instance);
  partial void DeletetblPaymentHistory(tblPaymentHistory instance);
  partial void InserttblShopCategory(tblShopCategory instance);
  partial void UpdatetblShopCategory(tblShopCategory instance);
  partial void DeletetblShopCategory(tblShopCategory instance);
  partial void InserttblShopProductCategory(tblShopProductCategory instance);
  partial void UpdatetblShopProductCategory(tblShopProductCategory instance);
  partial void DeletetblShopProductCategory(tblShopProductCategory instance);
  partial void InserttblShopProductDetial(tblShopProductDetial instance);
  partial void UpdatetblShopProductDetial(tblShopProductDetial instance);
  partial void DeletetblShopProductDetial(tblShopProductDetial instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OnlineSurfingShoppingDBConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ChangePassword> ChangePasswords
	{
		get
		{
			return this.GetTable<ChangePassword>();
		}
	}
	
	public System.Data.Linq.Table<forget> forgets
	{
		get
		{
			return this.GetTable<forget>();
		}
	}
	
	public System.Data.Linq.Table<Login> Logins
	{
		get
		{
			return this.GetTable<Login>();
		}
	}
	
	public System.Data.Linq.Table<OrderHistory> OrderHistories
	{
		get
		{
			return this.GetTable<OrderHistory>();
		}
	}
	
	public System.Data.Linq.Table<Register> Registers
	{
		get
		{
			return this.GetTable<Register>();
		}
	}
	
	public System.Data.Linq.Table<ShopDetail> ShopDetails
	{
		get
		{
			return this.GetTable<ShopDetail>();
		}
	}
	
	public System.Data.Linq.Table<ShopDetial> ShopDetials
	{
		get
		{
			return this.GetTable<ShopDetial>();
		}
	}
	
	public System.Data.Linq.Table<tblComplexCategory> tblComplexCategories
	{
		get
		{
			return this.GetTable<tblComplexCategory>();
		}
	}
	
	public System.Data.Linq.Table<tblPaymentHistory> tblPaymentHistories
	{
		get
		{
			return this.GetTable<tblPaymentHistory>();
		}
	}
	
	public System.Data.Linq.Table<tblShopCategory> tblShopCategories
	{
		get
		{
			return this.GetTable<tblShopCategory>();
		}
	}
	
	public System.Data.Linq.Table<tblShopProductCategory> tblShopProductCategories
	{
		get
		{
			return this.GetTable<tblShopProductCategory>();
		}
	}
	
	public System.Data.Linq.Table<tblShopProductDetial> tblShopProductDetials
	{
		get
		{
			return this.GetTable<tblShopProductDetial>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChangePassword")]
public partial class ChangePassword : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _New_Password;
	
	private string _Confirm_Password;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNew_PasswordChanging(string value);
    partial void OnNew_PasswordChanged();
    partial void OnConfirm_PasswordChanging(string value);
    partial void OnConfirm_PasswordChanged();
    #endregion
	
	public ChangePassword()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[New Password]", Storage="_New_Password", DbType="VarChar(50)")]
	public string New_Password
	{
		get
		{
			return this._New_Password;
		}
		set
		{
			if ((this._New_Password != value))
			{
				this.OnNew_PasswordChanging(value);
				this.SendPropertyChanging();
				this._New_Password = value;
				this.SendPropertyChanged("New_Password");
				this.OnNew_PasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Confirm Password]", Storage="_Confirm_Password", DbType="VarChar(50)")]
	public string Confirm_Password
	{
		get
		{
			return this._Confirm_Password;
		}
		set
		{
			if ((this._Confirm_Password != value))
			{
				this.OnConfirm_PasswordChanging(value);
				this.SendPropertyChanging();
				this._Confirm_Password = value;
				this.SendPropertyChanged("Confirm_Password");
				this.OnConfirm_PasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.forget")]
public partial class forget : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _User_Name;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUser_NameChanging(string value);
    partial void OnUser_NameChanged();
    #endregion
	
	public forget()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="VarChar(50)")]
	public string User_Name
	{
		get
		{
			return this._User_Name;
		}
		set
		{
			if ((this._User_Name != value))
			{
				this.OnUser_NameChanging(value);
				this.SendPropertyChanging();
				this._User_Name = value;
				this.SendPropertyChanged("User_Name");
				this.OnUser_NameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Login")]
public partial class Login : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _User_Name;
	
	private string _Password;
	
	private System.Nullable<int> _Role;
	
	private string _LoginDate;
	
	private string _LoginTime;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUser_NameChanging(string value);
    partial void OnUser_NameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRoleChanging(System.Nullable<int> value);
    partial void OnRoleChanged();
    partial void OnLoginDateChanging(string value);
    partial void OnLoginDateChanged();
    partial void OnLoginTimeChanging(string value);
    partial void OnLoginTimeChanged();
    #endregion
	
	public Login()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string User_Name
	{
		get
		{
			return this._User_Name;
		}
		set
		{
			if ((this._User_Name != value))
			{
				this.OnUser_NameChanging(value);
				this.SendPropertyChanging();
				this._User_Name = value;
				this.SendPropertyChanged("User_Name");
				this.OnUser_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="Int")]
	public System.Nullable<int> Role
	{
		get
		{
			return this._Role;
		}
		set
		{
			if ((this._Role != value))
			{
				this.OnRoleChanging(value);
				this.SendPropertyChanging();
				this._Role = value;
				this.SendPropertyChanged("Role");
				this.OnRoleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginDate", DbType="VarChar(50)")]
	public string LoginDate
	{
		get
		{
			return this._LoginDate;
		}
		set
		{
			if ((this._LoginDate != value))
			{
				this.OnLoginDateChanging(value);
				this.SendPropertyChanging();
				this._LoginDate = value;
				this.SendPropertyChanged("LoginDate");
				this.OnLoginDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginTime", DbType="VarChar(50)")]
	public string LoginTime
	{
		get
		{
			return this._LoginTime;
		}
		set
		{
			if ((this._LoginTime != value))
			{
				this.OnLoginTimeChanging(value);
				this.SendPropertyChanging();
				this._LoginTime = value;
				this.SendPropertyChanged("LoginTime");
				this.OnLoginTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderHistory")]
public partial class OrderHistory : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _OrderId;
	
	private string _Amount;
	
	private string _Card;
	
	private string _ShipingAddress;
	
	private string _ProductName;
	
	private System.Nullable<int> _Qnty;
	
	private string _DateofPurches;
	
	private string _userid;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrderIdChanging(int value);
    partial void OnOrderIdChanged();
    partial void OnAmountChanging(string value);
    partial void OnAmountChanged();
    partial void OnCardChanging(string value);
    partial void OnCardChanged();
    partial void OnShipingAddressChanging(string value);
    partial void OnShipingAddressChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnQntyChanging(System.Nullable<int> value);
    partial void OnQntyChanged();
    partial void OnDateofPurchesChanging(string value);
    partial void OnDateofPurchesChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    #endregion
	
	public OrderHistory()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int OrderId
	{
		get
		{
			return this._OrderId;
		}
		set
		{
			if ((this._OrderId != value))
			{
				this.OnOrderIdChanging(value);
				this.SendPropertyChanging();
				this._OrderId = value;
				this.SendPropertyChanged("OrderId");
				this.OnOrderIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="NVarChar(MAX)")]
	public string Amount
	{
		get
		{
			return this._Amount;
		}
		set
		{
			if ((this._Amount != value))
			{
				this.OnAmountChanging(value);
				this.SendPropertyChanging();
				this._Amount = value;
				this.SendPropertyChanged("Amount");
				this.OnAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Card", DbType="VarChar(MAX)")]
	public string Card
	{
		get
		{
			return this._Card;
		}
		set
		{
			if ((this._Card != value))
			{
				this.OnCardChanging(value);
				this.SendPropertyChanging();
				this._Card = value;
				this.SendPropertyChanged("Card");
				this.OnCardChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipingAddress", DbType="VarChar(MAX)")]
	public string ShipingAddress
	{
		get
		{
			return this._ShipingAddress;
		}
		set
		{
			if ((this._ShipingAddress != value))
			{
				this.OnShipingAddressChanging(value);
				this.SendPropertyChanging();
				this._ShipingAddress = value;
				this.SendPropertyChanged("ShipingAddress");
				this.OnShipingAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(MAX)")]
	public string ProductName
	{
		get
		{
			return this._ProductName;
		}
		set
		{
			if ((this._ProductName != value))
			{
				this.OnProductNameChanging(value);
				this.SendPropertyChanging();
				this._ProductName = value;
				this.SendPropertyChanged("ProductName");
				this.OnProductNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qnty", DbType="Int")]
	public System.Nullable<int> Qnty
	{
		get
		{
			return this._Qnty;
		}
		set
		{
			if ((this._Qnty != value))
			{
				this.OnQntyChanging(value);
				this.SendPropertyChanging();
				this._Qnty = value;
				this.SendPropertyChanged("Qnty");
				this.OnQntyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateofPurches", DbType="VarChar(MAX)")]
	public string DateofPurches
	{
		get
		{
			return this._DateofPurches;
		}
		set
		{
			if ((this._DateofPurches != value))
			{
				this.OnDateofPurchesChanging(value);
				this.SendPropertyChanging();
				this._DateofPurches = value;
				this.SendPropertyChanged("DateofPurches");
				this.OnDateofPurchesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="VarChar(50)")]
	public string userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this.OnuseridChanging(value);
				this.SendPropertyChanging();
				this._userid = value;
				this.SendPropertyChanged("userid");
				this.OnuseridChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Register")]
public partial class Register : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _First_Name;
	
	private string _Last_Name;
	
	private string _Email_Id;
	
	private long _Password;
	
	private long _Confirm_Password;
	
	private string _Address;
	
	private string _Phone_Number;
	
	private string _Gender;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnEmail_IdChanging(string value);
    partial void OnEmail_IdChanged();
    partial void OnPasswordChanging(long value);
    partial void OnPasswordChanged();
    partial void OnConfirm_PasswordChanging(long value);
    partial void OnConfirm_PasswordChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPhone_NumberChanging(string value);
    partial void OnPhone_NumberChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    #endregion
	
	public Register()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string First_Name
	{
		get
		{
			return this._First_Name;
		}
		set
		{
			if ((this._First_Name != value))
			{
				this.OnFirst_NameChanging(value);
				this.SendPropertyChanging();
				this._First_Name = value;
				this.SendPropertyChanged("First_Name");
				this.OnFirst_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Last_Name
	{
		get
		{
			return this._Last_Name;
		}
		set
		{
			if ((this._Last_Name != value))
			{
				this.OnLast_NameChanging(value);
				this.SendPropertyChanging();
				this._Last_Name = value;
				this.SendPropertyChanged("Last_Name");
				this.OnLast_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Email_Id
	{
		get
		{
			return this._Email_Id;
		}
		set
		{
			if ((this._Email_Id != value))
			{
				this.OnEmail_IdChanging(value);
				this.SendPropertyChanging();
				this._Email_Id = value;
				this.SendPropertyChanged("Email_Id");
				this.OnEmail_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="BigInt NOT NULL")]
	public long Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Confirm_Password", DbType="BigInt NOT NULL")]
	public long Confirm_Password
	{
		get
		{
			return this._Confirm_Password;
		}
		set
		{
			if ((this._Confirm_Password != value))
			{
				this.OnConfirm_PasswordChanging(value);
				this.SendPropertyChanging();
				this._Confirm_Password = value;
				this.SendPropertyChanged("Confirm_Password");
				this.OnConfirm_PasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone_Number", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Phone_Number
	{
		get
		{
			return this._Phone_Number;
		}
		set
		{
			if ((this._Phone_Number != value))
			{
				this.OnPhone_NumberChanging(value);
				this.SendPropertyChanging();
				this._Phone_Number = value;
				this.SendPropertyChanged("Phone_Number");
				this.OnPhone_NumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShopDetails")]
public partial class ShopDetail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Name;
	
	private string _Address;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    #endregion
	
	public ShopDetail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(200)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(200)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShopDetials")]
public partial class ShopDetial : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Name;
	
	private string _Address;
	
	private string _Image;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    #endregion
	
	public ShopDetial()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(200)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(200)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarChar(MAX)")]
	public string Image
	{
		get
		{
			return this._Image;
		}
		set
		{
			if ((this._Image != value))
			{
				this.OnImageChanging(value);
				this.SendPropertyChanging();
				this._Image = value;
				this.SendPropertyChanged("Image");
				this.OnImageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblComplexCategory")]
public partial class tblComplexCategory : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _ComplexName;
	
	private string _ComplexDetails;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnComplexNameChanging(string value);
    partial void OnComplexNameChanged();
    partial void OnComplexDetailsChanging(string value);
    partial void OnComplexDetailsChanged();
    #endregion
	
	public tblComplexCategory()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComplexName", DbType="VarChar(50)")]
	public string ComplexName
	{
		get
		{
			return this._ComplexName;
		}
		set
		{
			if ((this._ComplexName != value))
			{
				this.OnComplexNameChanging(value);
				this.SendPropertyChanging();
				this._ComplexName = value;
				this.SendPropertyChanged("ComplexName");
				this.OnComplexNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComplexDetails", DbType="VarChar(MAX)")]
	public string ComplexDetails
	{
		get
		{
			return this._ComplexDetails;
		}
		set
		{
			if ((this._ComplexDetails != value))
			{
				this.OnComplexDetailsChanging(value);
				this.SendPropertyChanging();
				this._ComplexDetails = value;
				this.SendPropertyChanged("ComplexDetails");
				this.OnComplexDetailsChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPaymentHistory")]
public partial class tblPaymentHistory : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _ProductId;
	
	private System.Nullable<decimal> _Amount;
	
	private string _CardNo;
	
	private string _CardHolderName;
	
	private string _UserId;
	
	private string _DateOfPurches;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnProductIdChanging(string value);
    partial void OnProductIdChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnCardNoChanging(string value);
    partial void OnCardNoChanged();
    partial void OnCardHolderNameChanging(string value);
    partial void OnCardHolderNameChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnDateOfPurchesChanging(string value);
    partial void OnDateOfPurchesChanged();
    #endregion
	
	public tblPaymentHistory()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="VarChar(50)")]
	public string ProductId
	{
		get
		{
			return this._ProductId;
		}
		set
		{
			if ((this._ProductId != value))
			{
				this.OnProductIdChanging(value);
				this.SendPropertyChanging();
				this._ProductId = value;
				this.SendPropertyChanged("ProductId");
				this.OnProductIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Amount
	{
		get
		{
			return this._Amount;
		}
		set
		{
			if ((this._Amount != value))
			{
				this.OnAmountChanging(value);
				this.SendPropertyChanging();
				this._Amount = value;
				this.SendPropertyChanged("Amount");
				this.OnAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNo", DbType="VarChar(50)")]
	public string CardNo
	{
		get
		{
			return this._CardNo;
		}
		set
		{
			if ((this._CardNo != value))
			{
				this.OnCardNoChanging(value);
				this.SendPropertyChanging();
				this._CardNo = value;
				this.SendPropertyChanged("CardNo");
				this.OnCardNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardHolderName", DbType="VarChar(50)")]
	public string CardHolderName
	{
		get
		{
			return this._CardHolderName;
		}
		set
		{
			if ((this._CardHolderName != value))
			{
				this.OnCardHolderNameChanging(value);
				this.SendPropertyChanging();
				this._CardHolderName = value;
				this.SendPropertyChanged("CardHolderName");
				this.OnCardHolderNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(50)")]
	public string UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfPurches", DbType="VarChar(50)")]
	public string DateOfPurches
	{
		get
		{
			return this._DateOfPurches;
		}
		set
		{
			if ((this._DateOfPurches != value))
			{
				this.OnDateOfPurchesChanging(value);
				this.SendPropertyChanging();
				this._DateOfPurches = value;
				this.SendPropertyChanged("DateOfPurches");
				this.OnDateOfPurchesChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblShopCategory")]
public partial class tblShopCategory : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _ComplexId;
	
	private string _ShopName;
	
	private string _ShowDetials;
	
	private string _ImagePath;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnComplexIdChanging(System.Nullable<int> value);
    partial void OnComplexIdChanged();
    partial void OnShopNameChanging(string value);
    partial void OnShopNameChanged();
    partial void OnShowDetialsChanging(string value);
    partial void OnShowDetialsChanged();
    partial void OnImagePathChanging(string value);
    partial void OnImagePathChanged();
    #endregion
	
	public tblShopCategory()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComplexId", DbType="Int")]
	public System.Nullable<int> ComplexId
	{
		get
		{
			return this._ComplexId;
		}
		set
		{
			if ((this._ComplexId != value))
			{
				this.OnComplexIdChanging(value);
				this.SendPropertyChanging();
				this._ComplexId = value;
				this.SendPropertyChanged("ComplexId");
				this.OnComplexIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopName", DbType="VarChar(50)")]
	public string ShopName
	{
		get
		{
			return this._ShopName;
		}
		set
		{
			if ((this._ShopName != value))
			{
				this.OnShopNameChanging(value);
				this.SendPropertyChanging();
				this._ShopName = value;
				this.SendPropertyChanged("ShopName");
				this.OnShopNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowDetials", DbType="VarChar(50)")]
	public string ShowDetials
	{
		get
		{
			return this._ShowDetials;
		}
		set
		{
			if ((this._ShowDetials != value))
			{
				this.OnShowDetialsChanging(value);
				this.SendPropertyChanging();
				this._ShowDetials = value;
				this.SendPropertyChanged("ShowDetials");
				this.OnShowDetialsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePath", DbType="VarChar(MAX)")]
	public string ImagePath
	{
		get
		{
			return this._ImagePath;
		}
		set
		{
			if ((this._ImagePath != value))
			{
				this.OnImagePathChanging(value);
				this.SendPropertyChanging();
				this._ImagePath = value;
				this.SendPropertyChanged("ImagePath");
				this.OnImagePathChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblShopProductCategory")]
public partial class tblShopProductCategory : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _ShopId;
	
	private string _ProductName;
	
	private string _ProductCategory;
	
	private string _ProductImage;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnShopIdChanging(System.Nullable<int> value);
    partial void OnShopIdChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnProductCategoryChanging(string value);
    partial void OnProductCategoryChanged();
    partial void OnProductImageChanging(string value);
    partial void OnProductImageChanged();
    #endregion
	
	public tblShopProductCategory()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopId", DbType="Int")]
	public System.Nullable<int> ShopId
	{
		get
		{
			return this._ShopId;
		}
		set
		{
			if ((this._ShopId != value))
			{
				this.OnShopIdChanging(value);
				this.SendPropertyChanging();
				this._ShopId = value;
				this.SendPropertyChanged("ShopId");
				this.OnShopIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(50)")]
	public string ProductName
	{
		get
		{
			return this._ProductName;
		}
		set
		{
			if ((this._ProductName != value))
			{
				this.OnProductNameChanging(value);
				this.SendPropertyChanging();
				this._ProductName = value;
				this.SendPropertyChanged("ProductName");
				this.OnProductNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCategory", DbType="VarChar(50)")]
	public string ProductCategory
	{
		get
		{
			return this._ProductCategory;
		}
		set
		{
			if ((this._ProductCategory != value))
			{
				this.OnProductCategoryChanging(value);
				this.SendPropertyChanging();
				this._ProductCategory = value;
				this.SendPropertyChanged("ProductCategory");
				this.OnProductCategoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductImage", DbType="VarChar(50)")]
	public string ProductImage
	{
		get
		{
			return this._ProductImage;
		}
		set
		{
			if ((this._ProductImage != value))
			{
				this.OnProductImageChanging(value);
				this.SendPropertyChanging();
				this._ProductImage = value;
				this.SendPropertyChanged("ProductImage");
				this.OnProductImageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblShopProductDetials")]
public partial class tblShopProductDetial : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _ShopProductId;
	
	private string _Name;
	
	private System.Nullable<decimal> _MarketPrice;
	
	private System.Nullable<decimal> _DiscountPrice;
	
	private System.Nullable<decimal> _OurPrice;
	
	private string _Description;
	
	private string _Image;
	
	private System.Nullable<decimal> _Quantity;
	
	private System.Nullable<System.DateTime> _createdDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnShopProductIdChanging(System.Nullable<int> value);
    partial void OnShopProductIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMarketPriceChanging(System.Nullable<decimal> value);
    partial void OnMarketPriceChanged();
    partial void OnDiscountPriceChanging(System.Nullable<decimal> value);
    partial void OnDiscountPriceChanged();
    partial void OnOurPriceChanging(System.Nullable<decimal> value);
    partial void OnOurPriceChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    partial void OnQuantityChanging(System.Nullable<decimal> value);
    partial void OnQuantityChanged();
    partial void OncreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedDateChanged();
    #endregion
	
	public tblShopProductDetial()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopProductId", DbType="Int")]
	public System.Nullable<int> ShopProductId
	{
		get
		{
			return this._ShopProductId;
		}
		set
		{
			if ((this._ShopProductId != value))
			{
				this.OnShopProductIdChanging(value);
				this.SendPropertyChanging();
				this._ShopProductId = value;
				this.SendPropertyChanged("ShopProductId");
				this.OnShopProductIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketPrice", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> MarketPrice
	{
		get
		{
			return this._MarketPrice;
		}
		set
		{
			if ((this._MarketPrice != value))
			{
				this.OnMarketPriceChanging(value);
				this.SendPropertyChanging();
				this._MarketPrice = value;
				this.SendPropertyChanged("MarketPrice");
				this.OnMarketPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscountPrice", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> DiscountPrice
	{
		get
		{
			return this._DiscountPrice;
		}
		set
		{
			if ((this._DiscountPrice != value))
			{
				this.OnDiscountPriceChanging(value);
				this.SendPropertyChanging();
				this._DiscountPrice = value;
				this.SendPropertyChanged("DiscountPrice");
				this.OnDiscountPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OurPrice", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> OurPrice
	{
		get
		{
			return this._OurPrice;
		}
		set
		{
			if ((this._OurPrice != value))
			{
				this.OnOurPriceChanging(value);
				this.SendPropertyChanging();
				this._OurPrice = value;
				this.SendPropertyChanged("OurPrice");
				this.OnOurPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarChar(500)")]
	public string Image
	{
		get
		{
			return this._Image;
		}
		set
		{
			if ((this._Image != value))
			{
				this.OnImageChanging(value);
				this.SendPropertyChanging();
				this._Image = value;
				this.SendPropertyChanged("Image");
				this.OnImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Quantity
	{
		get
		{
			return this._Quantity;
		}
		set
		{
			if ((this._Quantity != value))
			{
				this.OnQuantityChanging(value);
				this.SendPropertyChanging();
				this._Quantity = value;
				this.SendPropertyChanged("Quantity");
				this.OnQuantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> createdDate
	{
		get
		{
			return this._createdDate;
		}
		set
		{
			if ((this._createdDate != value))
			{
				this.OncreatedDateChanging(value);
				this.SendPropertyChanging();
				this._createdDate = value;
				this.SendPropertyChanged("createdDate");
				this.OncreatedDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
